version: '3.8'

services:
  # Sua aplicação PHP com Apache
  app:
    build: .
    container_name: login_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # Seu banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: login_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login
    ports:
      - "3306:3306"

  # O gerenciador do Banco (PHPMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: login_phpmyadmin
    links:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db